name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Установка зависимостей для Ubuntu
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential zip
          cmake --version

      # Установка зависимостей для macOS (с исправлением предупреждения)
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install --formula cmake
          cmake --version

      # Установка зависимостей для Windows (с zip)
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          # Установка Chocolatey если нет
          if (-not (Test-Path "$env:ProgramData\chocolatey\choco.exe")) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }

          # Установка cmake и zip
          choco install cmake zip -y --no-progress
          refreshenv
          cmake --version
          zip --version

      # Сборка проекта
      - name: Configure and Build
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel 2

          # Создаем директорию для артефактов
          mkdir -p ../artifacts

          # Копируем результаты сборки
          case "$RUNNER_OS" in
            Linux)
              find . -executable -type f ! -name "*.so*" -exec cp {} ../artifacts/ \;
              ;;
            macOS)
              find . -perm +111 -type f ! -name "*.dylib" -exec cp {} ../artifacts/ \;
              ;;
            Windows)
              find . -type f \( -name "*.exe" -o -name "*.dll" \) -exec cp {} ../artifacts/ \;
              ;;
          esac

      # Проверка результатов
      - name: Verify artifacts
        shell: bash
        run: |
          echo "Artifacts directory contents:"
          ls -lh artifacts/
          if [ ! -z "$(ls -A artifacts/)" ]; then
            echo "Artifacts found:"
            ls -lh artifacts/*
          else
            echo "No artifacts found!"
            exit 1
          fi

      # Создание архивов (раздельные шаги для Windows)
      - name: Create package (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cd artifacts
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            tar czf ../Solver-${{ github.ref_name }}-Linux.tar.gz *
          else
            tar czf ../Solver-${{ github.ref_name }}-macOS.tar.gz *
          fi
          cd ..
          echo "Created package:"
          ls -lh Solver-*.tar.gz

      - name: Create package (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd artifacts
          zip -r ..\Solver-%GITHUB_REF_NAME%-Windows.zip *
          cd ..
          dir Solver-*.zip

      # Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Solver-${{ runner.os }}
          path: |
            Solver-*.tar.gz
            Solver-*.zip
          retention-days: 7
