name: Build and Release

on:
  push:
    tags: ['v*.*.*']  # Формат v1.0.0, v2.3.1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.28.5'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            zlib1g-dev

      - name: Configure project
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --parallel $(nproc)

      - name: Generate packages
        run: |
          cd build
          cpack -G "TGZ;ZIP;DEB"
          mkdir -p ../artifacts
          mv *.tar.gz *.zip *.deb ../artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/*
          retention-days: 3

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
