name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential zlib1g-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        timeout-minutes: 15
        run: |
          choco install cmake ninja -y --no-progress --ignore-checksums
          refreshenv

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release --parallel 2

      - name: Create packages
        run: |
          cd build
          if [ "$RUNNER_OS" == "Linux" ]; then
            cpack -G "TGZ"
            cpack -G "DEB" || true
          elif [ "$RUNNER_OS" == "macOS" ]; then
            cpack -G "ZIP"
          else
            cpack -G "ZIP;WIX"
          fi
          mkdir -p ../artifacts
          find . -maxdepth 1 -type f \( -name '*.tar.gz' -o -name '*.deb' -o -name '*.zip' -o -name '*.msi' \) -exec mv {} ../artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ runner.os }}
          path: build/artifacts/*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-packages

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-packages/**/*
          generate_release_notes: true
