name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake ninja -y --no-progress --ignore-checksums

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Create packages (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          cd build
          if [ "$RUNNER_OS" == "Linux" ]; then
            cpack -G "TGZ"
          else
            cpack -G "ZIP"
          fi
          mkdir -p ../artifacts
          find . -maxdepth 1 -type f \( -name '*.tar.gz' -o -name '*.zip' \) -exec mv {} ../artifacts/ \;

      - name: Create packages (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          cd build
          cpack -G ZIP
          if not exist ..\artifacts mkdir ..\artifacts
          move *.zip ..\artifacts\

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ runner.os }}
          path: build/artifacts/*
          retention-days: 7
