name: Build and Package

on:
  push:
    tags: ['v*.*.*']  # Формат тега: v1.0.0
  workflow_dispatch:

jobs:
  build-packages:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y cmake build-essential rpm
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install cmake
        fi

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Generate packages
      run: |
        cd build
        case "$RUNNER_OS" in
          "Linux")
            cpack -G "DEB;RPM;TGZ;ZIP"
            ;;
          "macOS")
            cpack -G "DragNDrop;ZIP"
            ;;
          "Windows")
            cpack -G "WIX;ZIP"
            ;;
        esac
        mkdir -p ../artifacts
        mv *.{deb,rpm,tar.gz,zip,dmg,msi} ../artifacts/ 2>/dev/null || true

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages-${{ runner.os }}
        path: artifacts/*
        retention-days: 5

  create-release:
    needs: build-packages
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: combined-artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          combined-artifacts/**/*.deb
          combined-artifacts/**/*.rpm
          combined-artifacts/**/*.msi
          combined-artifacts/**/*.dmg
          combined-artifacts/**/*.tar.gz
          combined-artifacts/**/*.zip
        body: |
          Automated release for ${{ github.ref_name }}
          Packages:
          - DEB/RPM (Linux)
          - DMG (macOS)
          - MSI (Windows)
          - Source archives (ZIP/TGZ)
