name: Release Pipeline

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Общие настройки
      - name: Setup directories
        shell: bash
        run: |
          mkdir -p artifacts/packages
          mkdir -p artifacts/binaries

      # Установка зависимостей для Windows
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install wixtoolset -y --no-progress --force
          choco install cmake -y --no-progress
          $wixPath = "${env:ProgramFiles(x86)}\WiX Toolset v3.14\bin"
          if (-not (Test-Path $wixPath)) {
              $wixPath = "${env:ProgramFiles}\WiX Toolset v3.14\bin"
          }
          echo "WIX_PATH=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "$wixPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          refreshenv
          cmake --version

      # Установка зависимостей для Linux
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential zip rpm uuid-runtime
          cmake --version

      # Установка зависимостей для macOS
      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew update
          brew install --formula cmake
          cmake --version

      # Подготовка WiX (только Windows)
      - name: Prepare WiX assets
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir -p assets
          # Минимальный файл лицензии RTF
          echo "{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}\\viewkind4\\uc1\\pard\\sa200\\sl276\\slmult1\\lang9\\f0\\fs22 Sample License\\par}" > LICENSE.rtf
          # Заглушка для иконки
          echo "dummy" > assets/icon.ico
          # Заглушки для изображений WiX
          mkdir -p assets
          echo "dummy" > assets/wix_banner.bmp
          echo "dummy" > assets/wix_dialog.bmp

      # Конфигурация и сборка
      - name: Configure and Build
        shell: bash
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel 2

      # Копирование бинарников
      - name: Copy binaries
        shell: bash
        run: |
          case "$RUNNER_OS" in
            Linux|macOS)
              find build -name "solver" -type f -exec cp {} artifacts/binaries/ \;
              ;;
            Windows)
              find build -name "solver.exe" -type f -exec cp {} artifacts/binaries/ \;
              ;;
          esac

      # Создание пакетов
      - name: Create packages
        shell: bash
        run: |
          cd build
          case "$RUNNER_OS" in
            Linux)
              cpack -G DEB -C Release && cp *.deb ../artifacts/packages/ || echo "DEB package failed"
              cpack -G RPM -C Release && cp *.rpm ../artifacts/packages/ || echo "RPM package failed"
              cpack -G TGZ -C Release && cp *.tar.gz ../artifacts/packages/ || echo "TGZ package failed"
              ;;
            Windows)
              cpack -G WIX -C Release && cp *.msi ../artifacts/packages/ || echo "MSI package failed"
              cpack -G ZIP -C Release && cp *.zip ../artifacts/packages/ || echo "ZIP package failed"
              ;;
            macOS)
              cpack -G DragNDrop -C Release && cp *.dmg ../artifacts/packages/ || echo "DMG package failed"
              cpack -G ZIP -C Release && cp *.zip ../artifacts/packages/ || echo "ZIP package failed"
              ;;
          esac

      # Проверка артефактов
      - name: Verify artifacts
        shell: bash
        run: |
          echo "Artifacts contents:"
          ls -lhR artifacts/
          if [ -z "$(ls -A artifacts/packages/ 2>/dev/null)" ]; then
            echo "##[error] No packages created!"
            exit 1
          fi

      # Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Solver-${{ runner.os }}
          path: |
            artifacts/*
          retention-days: 7

      # Создание релиза
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver ${{ github.ref_name }}
          files: |
            artifacts/packages/*
            artifacts/binaries/*
          draft: false
          prerelease: false
