name: Release Pipeline

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: write
  packages: write

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Установка зависимостей для Ubuntu
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y cmake build-essential zip rpm
          cmake --version

      # Установка зависимостей для macOS
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install --formula cmake
          cmake --version

      # Установка зависимостей для Windows
      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          try {
              # Установка Chocolatey если нужно
              if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
                  Set-ExecutionPolicy Bypass -Scope Process -Force
                  [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
                  iwr https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex
              }

              # Установка CMake и WiX
              choco install cmake --version=3.28.1 -y --no-progress
              choco install wixtoolset -y --no-progress --force
              refreshenv
              cmake --version
              heat.exe -?
          } catch {
              Write-Error "Failed to install dependencies: $_"
              exit 1
          }

      # Подготовка файлов для всех ОС
      - name: Prepare assets
        shell: bash
        run: |
          # Создаем минимальный LICENSE.rtf если его нет
          if [ ! -f LICENSE.rtf ]; then
              echo "{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}\\viewkind4\\uc1\\pard\\sa200\\sl276\\slmult1\\lang9\\f0\\fs22 Sample License Text\\par }" > LICENSE.rtf
          fi

          # Создаем assets директорию если ее нет
          mkdir -p assets

          # Для Windows создаем иконку если ее нет
          if [ "$RUNNER_OS" = "Windows" ] && [ ! -f assets/icon.ico ]; then
              echo "Placeholder icon" > assets/icon.ico
          fi

      # Сборка проекта
      - name: Configure and Build
        shell: bash
        run: |
          mkdir -p build
          cd build
          if [ "$RUNNER_OS" = "Windows" ]; then
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -DCPACK_WIX_UPGRADE_GUID="$(uuidgen || echo '00000000-0000-0000-0000-000000000000')" \
                  -DCPACK_WIX_PRODUCT_GUID="$(uuidgen || echo '11111111-1111-1111-1111-111111111111')" \
                  -DCPACK_WIX_LICENSE_RTF="../LICENSE.rtf" \
                  -DCPACK_WIX_PRODUCT_ICON="../assets/icon.ico"
          else
              cmake .. -DCMAKE_BUILD_TYPE=Release
          fi
          cmake --build . --config Release --parallel 2

      # Создание исходников (только для тегов)
      - name: Create source packages
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          mkdir -p artifacts/source
          git archive --format=tar.gz -o artifacts/source/Solver-${{ env.VERSION }}-src.tar.gz HEAD
          git archive --format=zip -o artifacts/source/Solver-${{ env.VERSION }}-src.zip HEAD

      # Создание пакетов (только для тегов)
      - name: Create packages
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          mkdir -p artifacts/packages
          cd build

          if [ "$RUNNER_OS" = "Linux" ]; then
              cpack -G DEB && cpack -G RPM
              cp *.deb *.rpm ../artifacts/packages/

          elif [ "$RUNNER_OS" = "macOS" ]; then
              cpack -G DragNDrop || cpack -G ZIP
              cp *.dmg *.zip ../artifacts/packages/ 2>/dev/null || :

          elif [ "$RUNNER_OS" = "Windows" ]; then
              # Создаем MSI пакет
              cpack -G WIX
              cp *.msi ../artifacts/packages/

              # Дополнительно создаем ZIP с бинарником
              mkdir -p solver-${{ env.VERSION }}-win64
              cp Release/solver.exe solver-${{ env.VERSION }}-win64/
              zip -r ../artifacts/packages/solver-${{ env.VERSION }}-win64.zip solver-${{ env.VERSION }}-win64
          fi

      # Копирование бинарных файлов
      - name: Copy binaries
        shell: bash
        run: |
          mkdir -p artifacts/binaries
          case "$RUNNER_OS" in
            Linux|macOS)
              find build -name "solver" -type f -exec cp {} artifacts/binaries/solver-${{ env.VERSION }} \;
              ;;
            Windows)
              find build -name "solver.exe" -type f -exec cp {} artifacts/binaries/solver-${{ env.VERSION }}.exe \;
              ;;
          esac

      # Проверка артефактов
      - name: Verify artifacts
        shell: bash
        run: |
          echo "Artifacts:"
          ls -lhR artifacts/
          [ -z "$(ls -A artifacts/)" ] && echo "No artifacts!" && exit 1

      # Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Solver-${{ runner.os }}
          path: artifacts/*
          retention-days: 7

      # Создание релиза (только для тегов)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Solver ${{ env.VERSION }}
          files: |
            artifacts/source/*
            artifacts/packages/*
            artifacts/binaries/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
