name: Release Pipeline

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Установка зависимостей для Linux
      - name: Установка зависимостей (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            cmake build-essential zip rpm \
            libjsoncpp-dev librhash-dev uuid-runtime
          cmake --version

      # Установка зависимостей для macOS
      - name: Установка зависимостей (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew update --quiet
          brew install cmake || brew upgrade cmake
          cmake --version

      # Установка зависимостей для Windows
      - name: Установка зависимостей (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install wixtoolset -y --no-progress --ignore-detected-reboot
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          refreshenv
          Write-Host "CMake version:"
          cmake --version
          Write-Host "WiX version:"
          light.exe -version
          candle.exe -version

      # Подготовка файлов для Windows (MSI)
      - name: Подготовка файлов для MSI
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          # Создаем необходимые директории
          New-Item -ItemType Directory -Path "assets" -Force | Out-Null

          # Создаем LICENSE.rtf
          $licenseRtf = @"
{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
\viewkind4\uc1\pard\sa200\sl276\slmult1\lang9\f0\fs22 Sample License Text\par }
"@
          $licenseRtf | Out-File -Encoding ASCII "LICENSE.rtf"

          # Создаем иконку
          [byte[]]$iconBytes = 0x00,0x00,0x01,0x00,0x01,0x00,0x10,0x10,0x00,0x00,0x01,0x00,0x20,0x00,0x68,0x04,
                              0x00,0x00,0x16,0x00,0x00,0x00,0x28,0x00,0x00,0x00,0x10,0x00,0x00,0x00,0x20,0x00,
                              0x00,0x00,0x01,0x00,0x20,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
                              0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
          [System.IO.File]::WriteAllBytes("assets\icon.ico", $iconBytes)

          # Создаем WXS файл
          $guid1 = [guid]::NewGuid().ToString().ToUpper()
          $guid2 = [guid]::NewGuid().ToString().ToUpper()
          $wxsContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" Name="Solver" Language="1033" Version="$env:GITHUB_REF_NAME.Replace('v','')" Manufacturer="YourCompany" UpgradeCode="$guid1">
    <Package InstallerVersion="200" Compressed="yes" Comments="Windows Installer Package"/>
    <Media Id="1" Cabinet="media1.cab" EmbedCab="yes"/>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLDIR" Name="Solver">
          <Component Id="ApplicationFiles" Guid="$guid2">
            <File Id="ApplicationFile" Source="build\Release\solver.exe"/>
          </Component>
        </Directory>
      </Directory>
    </Directory>
    <Feature Id="DefaultFeature" Level="1">
      <ComponentRef Id="ApplicationFiles"/>
    </Feature>
    <Icon Id="icon.ico" SourceFile="assets\icon.ico"/>
    <Property Id="ARPPRODUCTICON" Value="icon.ico"/>
  </Product>
</Wix>
"@
          $wxsContent | Out-File -Encoding UTF8 "installer.wxs"

      # Сборка проекта
      - name: Сборка проекта
        shell: bash
        run: |
          mkdir -p build
          cd build
          if [ "$RUNNER_OS" = "Windows" ]; then
            cmake .. -G "Visual Studio 17 2022" -A x64
          else
            cmake .. -DCMAKE_BUILD_TYPE=Release
          fi
          cmake --build . --config Release --parallel 2

      # Создание исходников (только для тегов)
      - name: Создание исходных пакетов
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          mkdir -p artifacts/source
          git archive --format=tar.gz -o "artifacts/source/Solver-${{ github.ref_name }}-src.tar.gz" HEAD
          git archive --format=zip -o "artifacts/source/Solver-${{ github.ref_name }}-src.zip" HEAD

      # Создание пакетов (только для тегов)
      - name: Создание пакетов
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          cd build
          case "$RUNNER_OS" in
            Linux)
              cpack -G DEB
              cpack -G RPM
              ;;
            macOS)
              cpack -G DragNDrop || cpack -G ZIP
              ;;
            Windows)
              # Создаем MSI через WiX
              candle.exe ../installer.wxs -out installer.wixobj
              light.exe -ext WixUIExtension installer.wixobj -out Solver-${{ github.ref_name }}.msi
              # Создаем ZIP архив
              cpack -G ZIP -C Release
              ;;
          esac
          mkdir -p ../artifacts/packages
          cp *.deb *.rpm *.dmg *.msi *.zip ../artifacts/packages/ 2>/dev/null || :

      # Проверка результатов
      - name: Проверка артефактов
        shell: bash
        run: |
          echo "=== Структура артефактов ==="
          find artifacts/ -type f -exec ls -lh {} \;
          if [ ! -d "artifacts" ] || [ -z "$(ls -A artifacts/)" ]; then
            echo "::error::Артефакты не были созданы!"
            exit 1
          fi

      # Загрузка артефактов
      - name: Загрузка артефактов
        uses: actions/upload-artifact@v4
        with:
          name: Solver-${{ runner.os }}
          path: artifacts/
          retention-days: 7

      # Создание релиза (только для тегов)
      - name: Создание релиза
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver ${{ github.ref_name }}
          files: |
            artifacts/source/*
            artifacts/packages/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          body: |
            Автоматический релиз версии ${{ github.ref_name }}
            ### Доступные пакеты:
            - Исходный код (.tar.gz, .zip)
            - Пакеты для Linux (.deb, .rpm)
            - Пакет для macOS (.dmg)
            - Пакет для Windows (.msi)
