name: Release Pipeline

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: write
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Установка зависимостей
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            cmake build-essential zip rpm \
            libjsoncpp-dev librhash-dev uuid-runtime
          cmake --version

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew update --quiet
          brew install --formula cmake || brew upgrade cmake
          cmake --version

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install wixtoolset -y --no-progress --ignore-detected-reboot
          refreshenv
          Write-Host "WiX version:"
          light.exe -version
          candle.exe -version

      # Подготовка файлов для Windows
      - name: Prepare Windows files
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir -p assets
          # Создаем минимальные необходимые файлы
          echo "{\\rtf1\\ansi\\deff0{\\fonttbl{\\f0\\fnil\\fcharset0 Calibri;}}\\viewkind4\\uc1\\pard\\sa200\\sl276\\slmult1\\lang9\\f0\\fs22 Sample License Text\\par }" > LICENSE.rtf
          echo "Placeholder" > assets/icon.ico

      # Сборка проекта
      - name: Configure and Build
        shell: bash
        run: |
          mkdir -p build
          cd build
          if [ "$RUNNER_OS" = "Windows" ]; then
            cmake .. -G "Visual Studio 17 2022" -A x64 -DCPACK_GENERATOR="WIX;ZIP" -DCPACK_WIX_UPGRADE_GUID="$(uuidgen)" -DCPACK_WIX_PRODUCT_GUID="$(uuidgen)"
          else
            cmake .. -DCMAKE_BUILD_TYPE=Release
          fi
          cmake --build . --config Release --parallel 2

      # Создание исходников (только для тегов)
      - name: Create source packages
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          mkdir -p artifacts/source
          git archive --format=tar.gz -o "artifacts/source/Solver-${{ github.ref_name }}-src.tar.gz" HEAD
          git archive --format=zip -o "artifacts/source/Solver-${{ github.ref_name }}-src.zip" HEAD

      # Создание пакетов (только для тегов)
      - name: Create packages
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          cd build
          case "$RUNNER_OS" in
            Linux)
              cpack -G DEB || echo "DEB package creation failed"
              cpack -G RPM || echo "RPM package creation failed"
              ;;
            macOS)
              cpack -G DragNDrop || cpack -G ZIP || echo "Package creation failed"
              ;;
            Windows)
              echo "Creating Windows packages..."
              # Пытаемся создать MSI через CPack
              if ! cpack -G WIX -C Release; then
                echo "CPack WIX failed, trying manual build..."
                # Вручную создаем MSI если CPack не сработал
                candle.exe ../CMakeFiles/*.wxs -out installer.wixobj || echo "WXS compilation failed"
                light.exe -ext WixUIExtension installer.wixobj -out Solver-${{ github.ref_name }}.msi || echo "MSI linking failed"
              fi
              # Всегда создаем ZIP
              cpack -G ZIP -C Release || echo "ZIP creation failed"
              ;;
          esac
          mkdir -p ../artifacts/packages
          cp *.deb *.rpm *.dmg *.msi *.zip ../artifacts/packages/ 2>/dev/null || :

      # Копирование бинарных файлов
      - name: Copy binaries
        shell: bash
        run: |
          mkdir -p artifacts/binaries
          case "$RUNNER_OS" in
            Linux|macOS)
              find build -name "solver" -type f -exec cp {} artifacts/binaries/ \;
              ;;
            Windows)
              find build -name "solver.exe" -type f -exec cp {} artifacts/binaries/ \;
              ;;
          esac

      # Проверка результатов
      - name: Verify artifacts
        shell: bash
        run: |
          echo "=== Artifacts structure ==="
          find artifacts/ -type f -exec ls -lh {} \;
          if [ ! -d "artifacts" ] || [ -z "$(ls -A artifacts/)" ]; then
            echo "::error::No artifacts were generated!"
            exit 1
          fi
          echo "=== Package contents ==="
          case "$RUNNER_OS" in
            Linux)   ls -lh artifacts/packages/*.deb artifacts/packages/*.rpm 2>/dev/null || : ;;
            macOS)   ls -lh artifacts/packages/*.dmg artifacts/packages/*.zip 2>/dev/null || : ;;
            Windows)
              ls -lh artifacts/packages/*.msi artifacts/packages/*.zip 2>/dev/null || :
              if ls artifacts/packages/*.msi 1> /dev/null 2>&1; then
                echo "MSI package created successfully"
              else
                echo "::error::MSI package was not created"
                exit 1
              fi
              ;;
          esac

      # Дополнительная проверка для Windows
      - name: Verify MSI package (Windows)
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/')
        shell: powershell
        run: |
          $msi = Get-ChildItem artifacts\packages\*.msi
          if (-not $msi) {
            Write-Error "No MSI package found!"
            exit 1
          }
          Write-Host "MSI package verified: $($msi.FullName)"
          Write-Host "File size: $($msi.Length/1KB) KB"

      # Загрузка артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Solver-${{ runner.os }}
          path: artifacts/
          retention-days: 7

      # Создание релиза (только для тегов)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Solver ${{ github.ref_name }}
          files: |
            artifacts/source/*
            artifacts/packages/*
            artifacts/binaries/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          body: |
            Automated release for version ${{ github.ref_name }}
            ### Assets:
            - Binary packages (.deb, .rpm, .dmg, .msi, .zip)
            - Source code archives
